/**
 * Format subscription links as Clash-compatible YAML
 */

/**
 * @param {string[]} links - Array of VLESS/TROJAN links
 * @param {object} config - Loaded configuration
 * @returns {string} YAML-formatted subscription content
 */
export function formatAsClash(links, config) {
    const host = config.host || 'githubvpn.tepid.de5.net';
    const uuid = config.uuid;
    
    let yaml = `# Generated by cf-workers-sub\nport: 7890\nsocks-port: 7891\nallow-lan: true\nmode: Rule\nlog-level: info\nproxies:\n`;
    
    // Generate VLESS proxy entries
    const proxies = [
        { name: 'NYC', ip: host, lat: 40.7128, lng: -74.006 },
        { name: 'Tokyo', ip: host, lat: 35.6762, lng: 139.6503 },
        { name: 'London', ip: host, lat: 51.5074, lng: -0.1278 },
        { name: 'Singapore', ip: host, lat: 1.3521, lng: 103.8198 },
    ];
    
    for (const p of proxies) {
        yaml += `- name: "${p.name}"\n`;
        yaml += `  type: vless\n`;
        yaml += `  server: ${host}\n`;
        yaml += `  port: 443\n`;
        yaml += `  uuid: ${uuid}\n`;
        yaml += `  network: ws\n`;
        yaml += `  udp: true\n`;
        yaml += `  tls: true\n`;
        yaml += `  servername: ${host}\n`;
        yaml += `  client-fingerprint: firefox\n`;
        yaml += `  ws-opts:\n`;
        yaml += `    path: /${uuid}/?ed=2048\n`;
        yaml += `    headers:\n`;
        yaml += `      Host: ${host}\n`;
        yaml += `\n`;
    }
    
    yaml += `proxy-groups:\n  - name: LoadBalance\n    type: load-balance\n    url: https://www.gstatic.com/generate_204\n    interval: 300\n    strategy: round-robin\n    proxies:\n      ${proxies.map(p => '- ' + p.name).join('\n      ')}\n\n  - name: Select\n    type: select\n    proxies:\n      - LOAD-BALANCE\n      - DIRECT\n      ${proxies.map(p => '- ' + p.name).join('\n      ')}\n`;
    
    return yaml;
}
